### ISSUE TITLE
Is that an Exercise ?

### ISSUE THREAD

**Issue by awasum** [kelvinikome/Java-how-to-program#1]
https://github.com/kelvinikome/Java-how-to-program/blob/804cd06d021d2c9b3dcf993a37f9e0c158c2f9e5/Chapter%208/Exercise8_10.java#L3

**Comment by kelvinikome** [comment]
I was stuck with assigning parameters to enums so, I skipped it. I
later came back and completed it

https://github.com/kelvinikome/Java-how-to-program/blob/master/Chapter%208/Exercise8_10.java

**Comment by awasum** [comment]
Ok
